# Generated by Django 4.1.3 on 2024-05-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GirisYap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('sifre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=255)),
                ('soyisim', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('sifre', models.CharField(max_length=255)),
                ('sifre_dogrulama', models.CharField(max_length=20)),
                ('hesap_tipi', models.CharField(choices=[('Kullanici', 'Kullanici'), ('Restoran', 'Restoran')], max_length=20)),
            ],
        ),
    ]
