# Generated by Django 4.1.3 on 2024-04-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=255)),
                ('soyisim', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('parola', models.CharField(max_length=255)),
            ],
        ),
    ]
