# Generated by Django 4.1.3 on 2024-05-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GirisYap',
        ),
    ]
