# Generated by Django 5.0.6 on 2024-05-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_girisyap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
