# Generated by Django 5.0.6 on 2024-05-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_kullanici_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanici',
            name='sifre_dogrulama',
        ),
    ]
