# Generated by Django 5.0.6 on 2024-05-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_kullanici_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='dogum_gunu',
            field=models.DateTimeField(default=''),
        ),
    ]
