# Generated by Django 5.0.6 on 2024-05-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_kullanici_telefon_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
