# Generated by Django 5.0.6 on 2024-05-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_kullanici_dogum_gunu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanici',
            name='dogum_gunu',
        ),
    ]
