# Generated by Django 5.0.6 on 2024-05-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_kullanici_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kullanici',
            old_name='sifre',
            new_name='password',
        ),
    ]
