# Generated by Django 5.0.6 on 2024-05-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_sifre_kullanici_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kullanici',
            old_name='password',
            new_name='sifre',
        ),
    ]
