# Generated by Django 5.0.6 on 2024-05-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_password_kullanici_sifre'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
