# Generated by Django 4.1.3 on 2024-04-19 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=11)),
                ('adres', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RestoranDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restoran_name', models.CharField(max_length=255)),
                ('adres', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=10)),
                ('acilis_saati', models.TimeField()),
                ('kapanis_saati', models.TimeField()),
                ('puan', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('resim', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_tarihi', models.DateTimeField(auto_now_add=True)),
                ('teslim_tarihi', models.DateField()),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('durum', models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Onaylandı', 'Onaylandı'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi')], max_length=20)),
                ('mus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YemekSepeti.musteri')),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiparisDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.PositiveIntegerField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siparis_detaylari', to='YemekSepeti.siparis')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YemekSepeti.urun')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YemekSepeti.category')),
            ],
        ),
    ]
