# Generated by Django 5.0.6 on 2024-05-15 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_kullanici_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OdemeBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kart_sahibi', models.CharField(max_length=100)),
                ('kart_numarasi', models.IntegerField()),
                ('son_kullanma', models.IntegerField()),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=15)),
                ('acilisSaati', models.TimeField()),
                ('kapanis_saati', models.TimeField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('puan', models.FloatField(verbose_name=())),
                ('resim', models.ImageField(upload_to='')),
                ('min_tutar', models.FloatField(verbose_name=())),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_tarihi', models.DateTimeField(auto_now_add=True)),
                ('teslim_tarihi', models.DateField()),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('durum', models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Onaylandı', 'Onaylandı'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeslimatAdresi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('il', models.CharField(max_length=50)),
                ('ilce', models.CharField(max_length=50)),
                ('mahalle', models.CharField(max_length=50)),
                ('cadde', models.CharField(max_length=50)),
                ('bina', models.CharField(max_length=50)),
                ('kapi', models.CharField(max_length=50)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.kullanici')),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('fiyat', models.FloatField()),
                ('detay', models.TextField()),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='YemekSepeti.category')),
                ('restoran', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='YemekSepeti.restoran')),
            ],
        ),
        migrations.CreateModel(
            name='SiparisDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.PositiveIntegerField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siparis_detaylari', to='YemekSepeti.siparis')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YemekSepeti.urun')),
            ],
        ),
    ]
