# Generated by Django 5.0.6 on 2024-05-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YemekSepeti', '0002_alter_siparis_tutar_alter_siparisdetay_fiyat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restoran',
            old_name='acilisSaati',
            new_name='acilis_saati',
        ),
    ]
