# Generated by Django 4.1.3 on 2024-04-30 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YemekSepeti', '0002_siparis_sip_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urun',
            old_name='description',
            new_name='detay',
        ),
        migrations.RenameField(
            model_name='urun',
            old_name='price',
            new_name='fiyat',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='urun',
        ),
        migrations.AddField(
            model_name='restorandetay',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='restorandetay',
            name='min_tutar',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2),
        ),
        migrations.AddField(
            model_name='urun',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='YemekSepeti.category'),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
