# Generated by Django 4.1.3 on 2024-05-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YemekSepeti', '0003_rename_description_urun_detay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdemeBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kart_sahibi', models.CharField(max_length=100)),
                ('kart_numarasi', models.IntegerField()),
                ('son_kullanma', models.IntegerField()),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeslimatAdresi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('il', models.CharField(max_length=50)),
                ('ilce', models.CharField(max_length=50)),
                ('mahalle', models.CharField(max_length=50)),
                ('cadde', models.CharField(max_length=50)),
                ('bina', models.CharField(max_length=50)),
                ('kapi', models.CharField(max_length=50)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YemekSepeti.musteri')),
            ],
        ),
    ]
