# Generated by Django 5.0.6 on 2024-05-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YemekSepeti', '0003_rename_acilissaati_restoran_acilis_saati'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparisdetay',
            name='fiyat',
        ),
    ]
