# Generated by Django 4.1.3 on 2024-05-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YemekSepeti', '0004_odemebilgileri_teslimatadresi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='id',
        ),
        migrations.AddField(
            model_name='restoran',
            name='urun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='YemekSepeti.urun'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='urun_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
