# Generated by Django 5.0.6 on 2024-05-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YemekSepeti', '0004_remove_siparisdetay_fiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoran',
            name='hesap_tipi',
            field=models.CharField(choices=[('Kullanici', 'Kullanici'), ('Restoran', 'Restoran')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='restoran',
            name='sifre',
            field=models.CharField(default='', max_length=20),
        ),
    ]
