# Generated by Django 5.0.6 on 2024-05-29 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YemekSepeti', '0005_restoran_hesap_tipi_restoran_sifre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparis',
            name='durum',
        ),
        migrations.RemoveField(
            model_name='siparis',
            name='siparis_tarihi',
        ),
        migrations.RemoveField(
            model_name='siparis',
            name='teslim_tarihi',
        ),
        migrations.RemoveField(
            model_name='siparis',
            name='tutar',
        ),
        migrations.CreateModel(
            name='SiparisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_tarihi', models.DateTimeField(auto_now_add=True)),
                ('teslim_tarihi', models.DateField()),
                ('tutar', models.FloatField()),
                ('miktar', models.PositiveIntegerField()),
                ('durum', models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Onaylandı', 'Onaylandı'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi')], max_length=20)),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siparis_items', to='YemekSepeti.siparis')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YemekSepeti.urun')),
            ],
        ),
        migrations.DeleteModel(
            name='SiparisDetay',
        ),
    ]
